### ISSUE TITLE
Trouble running example config

### ISSUE THREAD

**Issue by hammerandtongs** [alphapapa/yequake#12] opened 2019-02-19 02:46 UTC
```
(use-package yequake
  :ensure t
  :custom
  (yequake-frames
   '(("org-capture"
      (buffer-fns . (yequake-org-capture))
      (width . 0.75)
      (height . 0.5)
      (alpha . 0.95)
      (frame-parameters . ((undecorated . t)
                           (skip-taskbar . t)
                           (sticky . t)))))))
```
issuing the command gives me

> ~/.emacs.d$ emacsclient -n -e '(yequake-toggle "org-capture")'
> 
> *ERROR*: Invalid function: (frame (alist-get name yequake-frames nil nil #'string=))

Here is the debug from running same command from eval

> Debugger entered--Lisp error: (invalid-function (frame (alist-get name yequake-frames nil nil #'string=)))
>   (frame (alist-get name yequake-frames nil nil #'string=))()
>   yequake-toggle("org-capture")
>   eval((yequake-toggle "org-capture") nil)
>   eval-expression((yequake-toggle "org-capture") nil nil 127)
>   funcall-interactively(eval-expression (yequake-toggle "org-capture") nil nil 127)
>   call-interactively(eval-expression nil nil)
>   command-execute(eval-expression)

This was with 25.1 and 27.0.50

**Comment by alphapapa** [comment] 2019-02-19 05:33
It appears that your Emacs lacks the `if-let*` macro.

**Comment by hammerandtongs** [comment] 2019-02-19 05:44
describe function if-let*

> if-let* is a Lisp macro.
> 
> (if-let* VARLIST THEN &rest ELSE)
> 
> Bind variables according to VARLIST and evaluate THEN or ELSE.
> This is like ‘if-let’ but doesn’t handle a VARLIST of the form
> (SYMBOL SOMETHING) specially.

This is emacs 27.0.50 but same errors on 25.1

I see you have 

`;; For Emacs <26

(unless (fboundp 'if-let*)
  (defalias 'if-let* 'if-let))
(unless (fboundp 'when-let*)
  (defalias 'when-let* 'when-let))
`
but that doesn't look like it would have put that documentation in my running emacs?

**Comment by alphapapa** [comment] 2019-02-20 02:22
Something is probably wrong with the way you installed the package, or other packages it depends on.  There's nothing wrong with the package itself, as it works fine for me and other users, as well as in the MELPA sandbox.

If you are using the same `~/.emacs.d` for Emacs 25.1 and 26+, you should expect problems due to incompatible changes, byte-code, etc.

**Comment by alphapapa** [comment] 2019-02-20 02:26
See also https://github.com/alphapapa/yequake/issues/11

Closing this issue since it's not a bug, but please let me know when you find the problem.

**Closed as completed by alphapapa** 2019-02-20 02:26 UTC
Labels: invalid

**Comment by hammerandtongs** [comment] 2019-02-24 01:50
Forcing a byte compile did fix this issue on 27+, I didn't go back and check 25.1 yet.

The initial window now loads but it fails to go away when toggle is called again with same parameter.

nil returned on initial window creation and t returned when trying to toggle it closed.

Kwin 5.12 fwiw.
